listen_addresses = '*'
max_connections = 100
shared_buffers = 128MB
dynamic_shared_memory_type = posix
max_wal_size = 1GB
min_wal_size = 80MB

logging_collector = on
log_directory = 'logs'
log_filename = 'postgresql-%a.log'
log_rotation_age = 1d
log_rotation_size = 0
log_truncate_on_rotation = on

log_timezone = 'UTC'
datestyle = 'iso, mdy'
timezone = 'UTC'

default_text_search_config = 'pg_catalog.english'

shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = all
