# Порт services.dnsmasq из NixOS 06-wifi-ap. Интерфейс AP поднимает NetworkManager (Wifi.nmconnection).

no-hosts
no-resolv
domain-needed
bogus-priv

interface=wlp2s0
listen-address=10.10.10.1
port=53
bind-interfaces

domain=domain.local
local=/domain.local/
address=/domain.local/10.10.10.1
dhcp-range=10.10.10.2,10.10.10.50,12h
